force-app/main/default/objects/Account/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Education</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/Job_Applicants__c.object-meta.xml
<CustomObject>
    <label>Job Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Job Applicants Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Applicants__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applicants</relationshipLabel>
    <relationshipName>Job_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Current_Title__c.field-meta.xml
<CustomField>
    <fullName>Current_Title__c</fullName>
    <label>Current Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Education</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Manager_Experience__c.field-meta.xml
<CustomField>
    <fullName>Manager_Experience__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager Experience</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Applicants__c/fields/Miles_From_Location__c.field-meta.xml
<CustomField>
    <fullName>Miles_From_Location__c</fullName>
    <label>Miles From Location</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Education.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>High School</fullName>
    </customValue>
    <customValue>
        <fullName>Technical Training</fullName>
    </customValue>
    <customValue>
        <fullName>Degree in Progress - BS</fullName>
    </customValue>
    <customValue>
        <fullName>Degree in Progress - MS</fullName>
    </customValue>
    <customValue>
        <fullName>2 year college</fullName>
    </customValue>
    <customValue>
        <fullName>4 year college</fullName>
    </customValue>
    <customValue>
        <fullName>Masters</fullName>
    </customValue>
    <customValue>
        <fullName>Doctorate</fullName>
    </customValue>
    <customValue>
        <fullName>Professional (MD, JD, CPA)</fullName>
    </customValue>
    <masterLabel>Education</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/getApplicants.cls
public with sharing class getApplicants {
    @AuraEnabled
    public static List<SObject> getApplicantRecords(String currentTitle,
                                                    String currLocation, 
                                                    String currEducation, 
                                                    String currMiles,
                                                    Boolean currManagerExp, 
                                                    Boolean currVisaReqd, 
                                                    Boolean currUSCitizen){
                                                        //Decimal currMiles,
system.debug('in getApplicantRecords');
system.debug('currentTitle :'+currentTitle);
system.debug('currLocation :'+currLocation);
system.debug('currEducation :'+currEducation);
system.debug('currMiles :'+currMiles);
system.debug('currManagerExp :'+currManagerExp);
system.debug('currVisaReqd :'+currVisaReqd);
system.debug('currUSCitizen :'+currUSCitizen);

String whereClause = ' WHERE ';

if(!String.isEmpty(currentTitle)){
    whereClause = whereClause + ' Current_Title__c = ' + '\'' + currentTitle + '\''  + ' AND ';
}

if(!String.isEmpty(currLocation)){
    whereClause = whereClause + ' Current_Location__c = ' + '\'' + currLocation + '\''  + ' AND ';
}

if(!String.isEmpty(currEducation)){
    whereClause = whereClause + ' Education__c = ' + '\'' + currEducation + '\''  + ' AND ';
}

if(currManagerExp){
    whereClause = whereClause + ' Manager_Experience__c = '  + currManagerExp  + ' AND ';
}

if(currVisaReqd){
    whereClause = whereClause + ' Visa_Required__c = ' +  currVisaReqd  + ' AND ';
}


if(!String.isEmpty(currMiles)){
    whereClause = whereClause + ' Miles_From_Location__c <= '  + currMiles  + ' AND ';
}

whereClause = whereClause.removeEnd(' AND ');
String queryString = '';
if(whereClause == ' WHERE '){
    //display all records
    queryString = 'SELECT Name, candidate__r,Current_Title__c, Current_Location__c, Education__c  FROM Job_Applicants__c ';
}else{
    //display results based on filters
    queryString = 'SELECT Name,candidate__r, Current_Title__c, Current_Location__c, Education__c  FROM Job_Applicants__c ' + whereClause;
}




system.debug('queryString is: '+queryString);
List<SObject> results = Database.query(queryString);
System.debug('search results: '+results);
return results;


}
}